service: selenium-on-aws-lambda

frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.7
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-northeast-1
  deploymentBucket:
    name: selenium-on-aws-lambda-deployment-bucket
    maxPreviousDeploymentArtifacts: 3

package:
  individually: true
  exclude:
    - README.md
    - requirements.txt
    - layers/**
    - layers.zip

layers:
  chromedriver:
    name: chromedriver
    description: A chromedriver and a headless-chromium binary files.
    path: layers/chromedriver
    compatibleRuntimes: ${self:provider.runtime}
  selenium:
    name: selenium
    description: v 3.14.0
    path: layers/selenium
    compatibleRuntimes: ${self:provider.runtime}

functions:
  func:
    handler: handler.func
    memorySize: 1024
    timeout: 300
    layers:
      - { Ref: ChromedriverLambdaLayer }
      - { Ref: SeleniumLambdaLayer }
